// react-wrapper.jsx
// react-wrapper.jsx
// Lightweight React wrapper for DataGrid
import React, { useEffect, useRef } from 'react';
// Assumes data-grid.js is available as an ES module

export default function DataGridReactWrapper({ apiEndpoint, columns }) {
  const gridRef = useRef(null);

  useEffect(() => {
    let gridInstance;
    import('./data-grid.js').then(({ DataGrid }) => {
      gridInstance = new DataGrid({
        container: gridRef.current,
        apiEndpoint,
        columns
      });
    });
    return () => {
      // Optionally: clean up if needed
      if (gridRef.current) gridRef.current.innerHTML = '';
    };
  }, [apiEndpoint, columns]);

  return (
    <div className="data-grid-container" ref={gridRef}></div>
  );
}

// angular-wrapper.ts
// angular-wrapper.ts
// Lightweight Angular wrapper for DataGrid
import { AfterViewInit, Component, ElementRef, Input, ViewChild } from '@angular/core';

@Component({
  selector: 'data-grid-angular',
  template: `<div #gridContainer class="data-grid-container"></div>`
})
export class DataGridAngularWrapper implements AfterViewInit {
  @Input() apiEndpoint!: string;
  @Input() columns: any[] = [];
  @ViewChild('gridContainer', { static: true }) gridContainer!: ElementRef;

  async ngAfterViewInit() {
    const module = await import('./data-grid.js');
    new module.DataGrid({
      container: this.gridContainer.nativeElement,
      apiEndpoint: this.apiEndpoint,
      columns: this.columns
    });
  }
}
